# Copyright 2026 The OpenFst Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Defines a pyx_library() and pyx_test() macros corresponding to
py_library.

Uses Cython to compile a .pyx file to a .c file, and then uses py_extension()
to compile the .c file to a python extension.

Example:
pyx_library(name = 'mylib',
            srcs = ['a.pyx', 'a.pxd', 'b.py', 'pkg/c.pyx'],
            cc_deps = ['//cc_library/dep'],
            py_deps = ['//py_library/dep', '//pxd_library/dep'],
            pxd_deps = ['//py_library/pyx_library', '//py_library/dep:dep_pxds']
            data = ['//other/data'],
)

This also creates a mylib_pxds target that can be depended on for cimporting
by placement in the py_deps portion of another pyx_library rule.  (Note that
the corresponding C libraries, if any, must still be manually placed in deps.)

For third-party libraries, make sure to include the __init__.py files in your
srcs list so that Cython can resolve cimports using the package layout. Note
that you need all the init files along the path to the cython files, e.g. if
your cython files are under a/b/cython/*, you need to include all of
__init__.py, a/__init__.py, a/b/__init__.py and a/b/cython/__init__.py

You can also use pyx_extension directly if there are non-trivial flags or
options that need to be used when building this extension, though generally
pyx_library is easier to use:

pyx_extension(name = 'pyxextension',
              srcs = ['myext.pyx'], # can only have 1
              module_name = 'myext'
)
"""

load("@bazel_skylib//lib:collections.bzl", "collections")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc/common:cc_common.bzl", "cc_common")
load("@rules_cc//cc/common:cc_info.bzl", "CcInfo")
load("@rules_python//python:py_library.bzl", "py_library")

def warn(msg):
    # buildifier: disable=print
    print("{red}{msg}{nc}".format(red = "\033[0;31m", msg = msg, nc = "\033[0m"))

PxdLibraryInfo = provider(
    doc = "Marks a target as a pxd_library.",
    fields = [],
)

def _pxd_cc_deps_impl(ctx):
    return [
        cc_common.merge_cc_infos(
            direct_cc_infos = [dep[CcInfo] for dep in ctx.attr.deps if PxdLibraryInfo in dep],
        ),
        PxdLibraryInfo(),
    ]

_pxd_cc_deps = rule(
    implementation = _pxd_cc_deps_impl,
    attrs = {
        "deps": attr.label_list(allow_files = True),
    },
)

def _pxd_library_impl(ctx):
    for dep in ctx.attr.deps:
        if CcInfo not in dep:
            if (dep.label.name.endswith("_proto") or
                dep.label.name.endswith("_protos") or
                dep.label.name.endswith("protos_all")):
                pass
            else:
                warn("pxd_library %s has dependency missing CcInfo: %s" % (ctx.label, dep.label))
    return [
        DefaultInfo(
            files = depset(
                ctx.files.srcs,
                transitive = [pxds[DefaultInfo].files for pxds in ctx.attr.deps],
            ),
        ),
        # All dependencies are considered direct dependencies as the generated .cc files will
        # directly include headers from transitive dependencies.
        # We add provide a separate layer_check target to ensure that any directly referenced
        # header files are exported by direct dependencies.
        cc_common.merge_cc_infos(
            direct_cc_infos = [dep[CcInfo] for dep in ctx.attr.deps if CcInfo in dep],
        ),
        PxdLibraryInfo(),
    ]

_pxd_library_rule = rule(
    implementation = _pxd_library_impl,
    attrs = {
        # TODO: Disallow arbitrary file extensions.
        "srcs": attr.label_list(allow_files = True),
        "deps": attr.label_list(),
    },
)

PyxInfo = provider(
    doc = ("On a py_extension generated by pyx_extension, provides the .py " +
           "or .pyx source used to generate the extension."),
    fields = {"pyx_src": "The .py or .pyx source."},
)

def _pyx_info_impl(ctx):
    # Note that we intentionally do not include pyx_src in runfiles, as
    # (1) we do not want it to count against file count limits, and
    # (2) it should not be considered eligible for import at runtime.
    return [PyxInfo(pyx_src = ctx.file.pyx_src)]

_pyx_info = rule(
    implementation = _pyx_info_impl,
    attrs = {
        "pyx_src": attr.label(allow_single_file = [".py", ".pyx"]),
    },
)

def _kwargs_add_values(kwargs, key, values):
    """Extends the values in the key `key` with values from `values`.

    This will handle if the data is missing, present, frozen, or a select()
    object in kwargs.

    Args:
        kwargs: kwargs dict. It will be modified in place.
        key: str, the key in `kwargs` to modify.
        values: list, the values to append.
    """
    existing = kwargs.pop(key, None)
    if existing == None:
        kwargs[key] = values
    else:
        # The existing value might be a select() object or frozen list, so we
        # have to add the two lists together
        kwargs[key] = existing + values

def _add_tags(kwargs, tags):
    """Appends each tag in `tags` to the tags key in `kwargs`.

    This will handle if tags is missing, present, or a select() object in kwargs.

    Args:
        kwargs: kwargs dict. It will be modified in place.
        tags: The list of tags to concat.
    """
    _kwargs_add_values(kwargs, "tags", tags)

def _copy_propagating_kwargs(outer_kwargs, inner_kwargs = None):
    """Copies args an outer target sets that an inner target must also set.

    This is intended for when the inner target is added as a dependency of
    the outer target, which requires that some settings propagate. e.g.,
    settings like `testonly` and `compatible_with` require the inner
    target to have compatible definitions with the outer target.

    Args:
        outer_kwargs: keyword args dict of the args from the outer target.
        inner_kwargs: optional keyword args dict for the inner target. Args
          in this take precedence over the ones in `outer_kwargs`.
          NOTE: This will be modified in-place.

    Returns:
        Keyword args to use for the inner target derived from the outer target.
        If `inner_kwargs` was passed in, then that same object is returned.
    """
    if inner_kwargs == None:
        inner_kwargs = {}

    # Include tags because people generally expect tags to propagate
    for attr in ("testonly", "tags"):
        if attr in outer_kwargs and attr not in inner_kwargs:
            inner_kwargs[attr] = outer_kwargs[attr]
    return inner_kwargs

def _canonicalize_cython_version(version):
    if version in (None, "3", "3.0", "3.0.10"):
        return "3_0_10"
    else:
        fail("Unsupported Cython version: %s" % version)

def split_ext(path):
    ix = path.rfind(".")
    if ix == -1:
        return path, ""
    else:
        return path[:ix], path[ix:]

CYTHON_EXTENSIONS = (".pyx", ".pxd", ".pxi", ".py")

C_EXTENSIONS = (".c", ".cc", ".h")

def _split_deps(name, deps, py_deps, pxd_deps, cc_deps):
    """Translates less strict deps args to the strict args."""
    true_cc_deps = cc_deps or []
    true_py_deps = []
    true_pxd_deps = pxd_deps or []

    if deps:
        for dep in deps:
            _, ext = split_ext(dep)
            if ext in CYTHON_EXTENSIONS:
                true_pxd_deps.append(dep)
            else:
                true_cc_deps.append(dep)
        warn(
            ("deps argument of rule %s is deprecated. " +
             "Move the cython dependencies to pxd_deps, " +
             "cc dependencies to cc_deps, " +
             "and python dependencies to py_deps.") %
            ("//" + native.package_name() + ":" + name),
        )

    if py_deps:
        for dep in py_deps:
            if dep.endswith("_pxds"):
                warn(("pxd library %s is listed in py_deps of rule %s. " +
                      "Treating it as a pxd_deps.") %
                     (dep, "//" + native.package_name() + ":" + name))
                true_pxd_deps.append(dep)
            else:
                true_py_deps.append(dep)

    return true_cc_deps, true_py_deps, true_pxd_deps

def pyx_library(
        name,
        srcs,
        deps = None,
        cc_deps = None,
        py_deps = None,
        pxd_deps = None,
        pyx_deps = None,
        cc_hdrs = None,
        data = None,
        deprecation = None,
        features = None,
        licenses = None,
        tags = None,
        testonly = None,
        visibility = None,
        pxd_visibility = None,
        pxd_compatible_with = None,
        py_library_rule = None,
        cc_only_deps = None,
        **extra_kwargs):
    """Creates a py_library with one or more cython-compiled extensions.

    Args:
      name: same as for py_library. A separate `{name}_pxds` target is created
          which other pyx_libraries may depend on for cimporting (note that
          _pxds target is a filegroup, so it doesn't propagate type information
          for pytype.)
      srcs: A list of .py, .pyx, and .pxd files.  Any .pyx file in the sources,
          as well as .py files with corresponding .pxd files, are compiled with
          Cython and linked in as extension modules.
      deps: Deprecated. A list of dependencies that are used in both the
          py_library and for C compilation of each of the Cython extension
          modules. Please use py_deps, cc_deps, or pxd_deps according
          to the type of the dependency.
      cc_deps: CC dependencies for the extension module Cython creates.
      py_deps: Dependencies of the final py_library. If a target ends with
          "_pxds", it is moved to pxd_deps for backward compatibility.
          A warning is issued when this happens. Pleasely move the
          "_pxds" target to pxd_deps.
      pxd_deps: pxd_library labels for Cython include files used in the
          compilation. File labels are also allowed.
      pyx_deps: deprecated. Replaced by pxd_deps.
      cc_hdrs: headers for extension module Cython creates.
      data: same as for py_library
      deprecation: same as for py_library
      features: same as for py_library
      licenses: same as for py_library
      tags: same as for py_library
      testonly: same as for py_library
      visibility: same as for py_library
      pxd_visibility: if given, a different visibility to use for the
          generated _pxds target.
      pxd_compatible_with: if given, a different compatible_with to use for
          the generated _pxds target.
      py_library_rule: rule to use for generated py_library
      cc_only_deps: same as cc_deps, Deprecated.
      **extra_kwargs: extra arguments to pass to the underlying
          pyx_extension rules
    """

    if pyx_deps:
        warn("in rule %s pyx_deps is deprecated. Use pxd_deps instead." %
             ("//" + native.package_name() + ":" + name))
        pxd_deps = pxd_deps or []
        pxd_deps.extend(pyx_deps)

    if cc_only_deps:
        warn("in rule %s cc_only_deps is deprecated. Use cc_deps instead." %
             ("//" + native.package_name() + ":" + name))
        cc_deps = cc_deps or []
        cc_deps.extend(cc_only_deps)

    cc_deps, py_deps, pxd_deps = _split_deps(
        name = name,
        deps = deps,
        py_deps = py_deps,
        pxd_deps = pxd_deps,
        cc_deps = cc_deps,
    )

    # TODO: Restrict pxd_deps to only pxd_library targets.
    actual_pxd_deps = name + "_pxd_deps"
    _pxd_cc_deps(
        name = actual_pxd_deps,
        deps = pxd_deps,
        testonly = testonly,
        compatible_with = extra_kwargs.get("compatible_with"),
    )

    cc_hdrs = cc_hdrs or []
    py_srcs = []
    for src in srcs:
        base, ext = split_ext(src)
        if ext in CYTHON_EXTENSIONS or ext in C_EXTENSIONS:
            if ext == ".py":
                py_srcs.append(src)
                if src.endswith("__init__.py"):
                    pxd_deps.append(src)
            elif ext in (".pxd", ".pxi"):
                pxd_deps.append(src)
            elif ext == ".h":
                cc_hdrs.append(src)
        else:
            py_srcs.append(src)

    rule_suffix = "_py_extension_rule"

    pyx_extensions = []
    pyx_so_files = []
    tags = tags or []
    for src in srcs:
        base, ext = split_ext(src)
        if ext == ".pyx" or (ext == ".py" and base + ".pxd" in srcs):
            pyx_rule = src.replace("/", "__") + rule_suffix
            pyx_extension(
                name = pyx_rule,
                srcs = [src] + cc_hdrs,
                cc_deps = cc_deps + [actual_pxd_deps],
                pxd_deps = pxd_deps,
                data = data,
                deprecation = deprecation,
                features = features,
                licenses = licenses,
                tags = tags + ["avoid_dep", "alt_dep=:%s" % name],
                testonly = testonly,
                visibility = ["//visibility:private"],
                **extra_kwargs
            )
            pyx_extensions.append(pyx_rule)
            rename_rule = pyx_rule + "_rename"
            native.genrule(
                name = rename_rule,
                srcs = [pyx_rule],
                outs = [split_ext(src.split("/")[-1])[0] + ".so"],
                cmd = "cp $< $@",
                testonly = testonly,
                visibility = ["//visibility:private"],
            )
            pyx_so_files.append(rename_rule)

    extra_py_library_args = {}
    for key in ("compatible_with", "pyi_srcs", "pytype_deps"):
        if key in extra_kwargs:
            extra_py_library_args[key] = extra_kwargs[key]

    if py_library_rule == None or py_library_rule == py_library:
        py_library_rule = py_library

    if py_srcs:
        # Add export_dep tags for extensions so they are visible to consumers.
        tags = list(tags or [])
        package_name = native.package_name()
        for src in srcs:
            base, ext = split_ext(src)
            if ext == ".pyx":
                # We only export extensions derived from .pyx files.
                # Extensions derived from .py files (with .pxd) are already visible because
                # the .py file itself is included in 'srcs', so strict deps knows about it.
                ext_target_name = src.replace("/", "__") + rule_suffix
                tags.append("export_dep=//%s:%s" % (package_name, ext_target_name))
        tags = collections.uniq(tags)

    py_library_rule(
        name = name,
        srcs = py_srcs,
        data = collections.uniq((data or []) + pyx_so_files),
        deps = py_deps + pyx_extensions,
        deprecation = deprecation,
        features = features,
        licenses = licenses,
        tags = tags,
        testonly = testonly,
        visibility = visibility,
        **extra_py_library_args
    )

    # TODO: Make depending on the pyx_library automatically depend
    # on this pxd_library (or at least the underlying set of pxd files).
    pxd_srcs = [src for src in srcs if src.endswith(".pxd") or src.endswith("/__init__.py")]
    if pxd_srcs:
        extra_pxd_library_args = {}
        if pxd_compatible_with:
            extra_pxd_library_args = {"compatible_with": pxd_compatible_with}
        elif "compatible_with" in extra_kwargs:
            extra_pxd_library_args = {"compatible_with": extra_kwargs["compatible_with"]}
        pxd_library(
            name = name + "_pxds",
            # Transitively include all dependenent pxd libraries in the library.
            srcs = collections.uniq(
                pxd_srcs + pxd_deps,
            ),
            deps = collections.uniq(cc_deps) + [actual_pxd_deps],
            testonly = testonly,
            visibility = pxd_visibility or visibility,
            **extra_pxd_library_args
        )

def pxd_library(name, srcs, deps = [], **kwargs):
    """A target for bundling .pxd files for use by other pyx_libraries.

    The pxd library transitively includes all dependent pxd_libraries.

    A pxd_library with the _pxds suffix is created for every pyx_library that
    contains .pxd files or __init__.py files.

    Args:
      name: The name of the build rule
      srcs: The .pxd files to include.
      deps: The pxd_library and cc_library targets that the .pxd files depend on.
      **kwargs: extra arguments to pass to the underlying cc_library rules
    """
    _pxd_library_rule(name = name, srcs = srcs, deps = deps, **kwargs)

def pyx_extension(
        name,
        srcs,
        deps = None,
        cc_deps = None,
        pxd_deps = None,
        pyx_deps = None,
        data = None,
        copts = None,
        testonly = None,
        cython_includes = [],
        cython_directives = None,
        cython_environment = None,
        cython_version = None,
        py_extension_rule = None,
        cpp = 1,
        generate_hdrs = False,
        generate_api = False,
        cc_only_deps = None,
        **extra_kwargs):
    """Generate a py_extension from a single .pyx or .py source.

    Args:
      name: The name of the build rule
      srcs: The .pyx or .py file to compile (must be a list with only one element)
      deps: Deprecated. A list of dependencies that are used in both the
          py_library and for C compilation of each of the Cython extension
          modules. Please use cc_deps, or pxd_deps according
          to the type of the dependency.
      cc_deps: CC dependencies for the extension module Cython creates.
      pxd_deps: pxd_library labels for Cython include files used in the
          compilation. File labels are also allowed.
      pyx_deps: deprecated. Replaced by pxd_deps.
      data: Data passed to generated py_extension.
      copts: Options to be passed to the C compiler
      testonly: Standard meaning
      cython_includes: include directories to add to cython pyx -> cc command
          (with -I)
      cython_directives: compiler directives to pass to cython pyx -> cc
          command (with -X)
      cython_environment: compile-time environment variables for cython (with -E)
      cython_version: Cython version to use.
      py_extension_rule: Name of rule to use to compile the generated .cc
      cpp: generate c++ code if true, else generate c code.
      generate_hdrs: if true, cython is expected to generate a header file as
          an output. This will be passed to the subsequent py_extension rule
          in textual_hdrs.
      generate_api: if true, cython is expected to generate an _apy.h header file as
          an output. This will be passed to the subsequent py_extension rule
          in textual_hdrs.
      cc_only_deps: Deprecated. Replaced by cc_deps.
      **extra_kwargs: passed to generated py_extension
    """
    c_srcs = []
    pyx_src = None
    module_name = extra_kwargs.pop("module_name", None)

    if pyx_deps:
        fail("in rule %s pyx_deps is deprecated. Use pxd_deps instead." %
             ("//" + native.package_name() + ":" + name))

    if cc_only_deps:
        fail("in rule %s cc_only_deps is deprecated. Use cc_deps instead." %
             ("//" + native.package_name() + ":" + name))

    if "outs" in extra_kwargs:
        fail("'outs' is not valid for pyx_extension", "outs")

    for src in srcs:
        base, ext = split_ext(src)
        if ext == ".pyx" or ext == ".py":
            if pyx_src == None:
                pyx_src = src
                if module_name == None:
                    module_name = base.replace("/", ".")
            else:
                fail('"srcs" can only have 1 pyx/py file')
        else:
            c_srcs.append(src)

    if pyx_src == None:
        fail('"srcs" must have 1 pyx/py file %s' % srcs)

    if module_name != None:
        extra_kwargs["module_name"] = module_name

    # Add generated_py_module tag.
    tags = extra_kwargs.pop("tags", [])
    base, _ = split_ext(pyx_src)
    generated_py_module = "{package_name}.{name}".format(
        package_name = native.package_name().replace("/", "."),
        name = base,
    )
    tags.append("generated_py_module={}".format(generated_py_module))

    if py_extension_rule == None:
        py_extension_rule = _py_extension
        if py_extension_rule == None:
            fail('"native.py_extension" must exist')

    cc_deps, py_deps, pxd_deps = _split_deps(
        name = name,
        deps = deps,
        py_deps = [],
        cc_deps = cc_deps or [],
        pxd_deps = [dep for dep in pxd_deps or []],
    )

    if len(py_deps) > 0:
        fail("py_deps shall be empty")

    file_prefix = "_cython/" + split_ext(pyx_src)[0]
    if cpp:
        cython_c_file = file_prefix + ".cc"
        cpp_flag = "--cplus"
    else:
        cython_c_file = file_prefix + ".c"
        cpp_flag = ""

    cython_hdrs = []
    if generate_hdrs:
        cython_hdrs.append(file_prefix + ".h")
    if generate_api:
        cython_hdrs.append(file_prefix + "_api.h")

    cython_args = (
        ["-I%s" % x for x in cython_includes] +
        ["-X%s" % x for x in cython_directives or []] +
        ["-E%s" % x for x in cython_environment or []] +
        ["-I.", "-2"]  # Avoid language_level warning.
    )

    extra_genrule_args = {}
    if "compatible_with" in extra_kwargs:
        extra_genrule_args = {"compatible_with": extra_kwargs["compatible_with"]}
    if "licenses" in extra_kwargs:
        extra_genrule_args["licenses"] = extra_kwargs["licenses"]

    cython_version = _canonicalize_cython_version(cython_version)
    cython_tool = "@cython//:cython_binary"

    native.genrule(
        name = name + "_cython",
        srcs = pxd_deps + ([] if pyx_src in pxd_deps else [pyx_src]),
        outs = [cython_c_file, file_prefix + ".html"] + cython_hdrs,
        tools = [cython_tool],
        cmd = " ".join([
            "PYTHONHASHSEED=0",
            "$(location %s)" % cython_tool,
            "$(location %s)" % pyx_src,
            cpp_flag,
            "--annotate",
            "-o $(location %s)" % cython_c_file,
        ] + cython_args),
        message = "Cythonize",
        testonly = testonly,
        visibility = ["//visibility:private"],
        **extra_genrule_args
    )

    if copts == None:
        copts = []

    if extra_kwargs.get("features", None) == None:
        extra_kwargs["features"] = []
    extra_kwargs["features"] = extra_kwargs["features"] + ["-use_header_modules"]

    if generate_hdrs:
        extra_kwargs["textual_hdrs"] = (extra_kwargs.get("textual_hdrs", []) +
                                        cython_hdrs)

    # We create a _pyx_info target and put it into data so that consumers of the
    # py_extension have access to it. In particular, the pytype aspect relies on
    # this to infer Python types for pyx_extension targets.
    pyx_info_name = name + "_pyx_info"

    # Copy fields like 'compatible_with' that should propagate to _pyx_info.
    pyx_info_kwargs = _copy_propagating_kwargs(extra_kwargs)

    # 'testonly' and 'tags' aren't in extra_kwargs, so we manually copy them.
    pyx_info_kwargs["testonly"] = testonly
    _add_tags(pyx_info_kwargs, tags)

    # Hide the pyx_info from tools and automation.
    _pyx_info(
        name = pyx_info_name,
        pyx_src = pyx_src,
        visibility = ["//visibility:private"],
        **pyx_info_kwargs
    )
    extra_kwargs["data"] = data
    _kwargs_add_values(extra_kwargs, "data", [":" + pyx_info_name])

    # Remove unsupported keys for `pybind_extension`.
    for arg_name in ["pyi_deps", "pyi_srcs", "pyi_srcs", "module_name"]:
        extra_kwargs.pop(arg_name, None)

    py_extension_rule(
        name = name,
        srcs = [cython_c_file] + c_srcs,
        deps = cc_deps,
        copts = copts,
        testonly = testonly,
        tags = tags,
        **extra_kwargs
    )

def _py_extension(
        name,
        srcs,
        deps = None,
        copts = None,
        linkopts = None,
        **kwargs):
    """Compiles a Python C extension module using native cc_binary."""
    copts = copts or []
    linkopts = linkopts or []
    deps = deps or []

    cc_binary(
        name = name,
        srcs = srcs,
        deps = deps + [
            "@rules_python//python/cc:current_py_cc_headers",
            "@rules_python//python/cc:current_py_cc_libs",
        ],
        copts = copts + select({
            "@platforms//os:windows": [],
            "//conditions:default": [
                # Position Independent Code (PIC) for shared libraries.
                "-fPIC",
                # Self-assignment generated in some degenerate cases (with the
                # correct no-op behavior.)
                "-Wno-self-assign",
                # These fall-throughs are intentional (but not documented as such).
                "-Wno-implicit-fallthrough",
                # Cython re-throws exceptions from stdlib to catch their error msgs.
                "-fexceptions",
            ],
        }),
        linkopts = select({
            "@platforms//os:macos": ["-undefined", "dynamic_lookup"],
            "//conditions:default": [],
        }) + linkopts,
        linkshared = True,
        **kwargs
    )
